[package]
name = "NootStandard"
version = "0.1.2"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
NootStandard = { local = "../noot_standard" }

[addresses]
noot_classic =  "0x0"
sui = "0x2"
noot = "0x3"
