[package]
name = "NootFactory"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
NootStandard = { local = "../noot_standard" }

[addresses]
sui = "0x2"
noot = "0x3"
factory = "0x0"